#!/bin/bash

set -e

# Ensure old_config directory exists
mkdir -p /host/security_cipher

# Copy cipher_pass file to persistent storage
if [ -f /etc/cipher_pass.json ]; then
    cp /etc/cipher_pass.json /host/security_cipher/cipher_pass.json 
    echo "Saved /etc/cipher_pass.json to /host/security_cipher/"
fi

